### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by ClarkLaneman** [Hozuki/DereTore#1]
Can you give a simple example how the decoder works. I tryed it this way but
it doesn't work. The file size gets bigger but the bool var "hasMore" never changes his state.

Another question, why must i call decoder.Initialize()? Why ist it not automatically called when i create the decoder object?

```C#
            byte[] buffer = new Byte[2048];
            bool hasMore = true;

            FileStream fs = File.OpenRead(@"E:\example.hca");
            HcaDecoder decoder = new HcaDecoder(fs);
            decoder.Initialize();

            decoder.WriteWaveHeader(buffer);

            FileStream fo = new FileStream(@"E:\wharg.wav", FileMode.CreateNew);
            fo.Write(buffer, 0, buffer.Length);

            if (buffer.Length >0)
            {
                while (hasMore ==true)
                {
                    decoder.DecodeData(buffer, out hasMore);
                    fo.Write(buffer, 0, buffer.Length);
                }

            }
            fo.Close();```

**Comment by Hozuki** [comment]
Hi Clark,

For the first question, I made a demo `DereTore.Application.Hca2Wav` to demonstrate the decoding process. It works fine with the HCA sample. You can download the sample [here](https://mega.nz/#!Bgp1jBrC!T7Z7BX0r5KTfztIHER9pVqnXc9nVOzUIqIs4aMXqWxM).

I think that you didn't gave the decoder a proper-sized buffer. During my test, the buffer should have a size of at least 0x1000(4096) bytes to enable the decoding. There are utility functions `HcaDecoder.GetWaveHeaderNeededLength()` and `HcaDecoder.GetWaveDataBlockNeededLength()` to confirm the minimum size buffers required. I forgot to throw an exception for buffers too small, and it will now. Please check the latest commit.

For the second question, it's my bad. I am just scared of throwing exceptions in constructors. After observing classes like `FileStream` I decided to make the initialization automatic. Now you don't need to manually call `Initialize()` anymore.
